
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='systa',
    version='0.1.0',
    description='Windows GUI automation with a cool API.',
    python_requires='==3.*,>=3.7.0',
    author='Dustin Wyatt',
    author_email='dustin.wyatt@gmail.com',
    license='MIT',
    packages=['systa', 'systa.backends', 'systa.events', 'systa.experimental', 'systa.scripts'],
    package_data={},
    install_requires=['argupdate', 'boltons==19.*,>=19.3.0', 'pywin32==226.*,>=226.0.0', 'pyzmq==18.*,>=18.1.0', 'typing-extensions==3.*,>=3.7.0', 'typing-inspect==0.*,>=0.5.0', 'wrapt==1.*,>=1.11.0'],
    dependency_links=['git+https://github.com/dmwyatt/argupdate.git#egg=argupdate'],
    extras_require={'dev': ['beautifulsoup4==4.*,>=4.8.0', 'ipython==7.*,>=7.9.0', 'pytest==5.*,>=5.3.0', 'sphinx==2.*,>=2.2.0', 'sphinx-autodoc-typehints==1.*,>=1.10.0']},
)
